---
title: "Benchmarking computational efficiency of TreeSE methods"
author: "Giulio Benedetti and Leo Lahti"
date: "`r Sys.Date()`"
---

```{r include = FALSE}
source("data.R", local = knitr::knit_global())
```

```{r dataframe, echo = FALSE}
# create NA data frame to store the execution times throughout the for loop
df <- data.frame(Features = rep(NA, len_set),
                 Samples = rep(NA, len_set),
		 BetaEstimation = rep(NA, len_set),
		 row.names = data_sets)

df <- rbind(df[rep(1:len_set, 2), ]) %>%
        mutate(ObjectType = c(rep("tse", len_set), rep("pseq", len_set)),
	       BetaCommand = c(rep("runMDS", len_set), rep("ordinate", len_set)),
	       AssayValues = rep("", 2 * len_set))
```

```{r iteration, echo = FALSE}
for (data_set in data_sets) {

  # define index of current data set
  cur_set <- which(data_sets == data_set)
  
  # extract tse and pseq from list of containers
  tse <- containers[[cur_set]][[1]]
  pseq <- containers[[cur_set]][[2]]
  
  # select big data sets at least as large as sample_size
  if (dim(tse)[2] >= sample_size) {
  
    # random subsetting
    subset_names <- sample(colnames(tse), sample_size)
    tse <- tse[ , colData(tse)@rownames %in% subset_names]

    # store dimensions
    df$Features[cur_set] <- dim(tse)[1]
    df$Features[cur_set + len_set] <- dim(tse)[1]
    df$Samples[cur_set] <- dim(tse)[2]
    df$Samples[cur_set + len_set] <- dim(tse)[2]

    if (condition_5[cur_set]) {

      # test beta diversity estimation for tse
      start.time1 <- Sys.time()
      beta_tse <- scater::runMDS(tse, FUN = vegan::vegdist, name = "MDS_BC", exprs_values = df$AssayValues[cur_set])
      pcoa_tse <- scater::plotReducedDim(beta_tse, "MDS_BC")
      end.time1 <- Sys.time()
      df$BetaEstimation[cur_set] <- end.time1 - start.time1

      # test beta diversity estimation for pseq
      start.time2 <- Sys.time()
      beta_pseq <- phyloseq::ordinate(pseq, "MDS", "bray")
      pcoa_pseq <- phyloseq::plot_ordination(pseq, beta_pseq, type = "samples")
      end.time2 <- Sys.time()
      df$BetaEstimation[cur_set + len_set] <- end.time2 - start.time2

    }
  
  }
  
}

rm("condition_1", "condition_2", "condition_3", "condition_4", "condition_5")
```

```{r beta_features}
ggplot(df, aes(x = Features, y = BetaEstimation, color = BetaCommand, shape = as.factor(Samples))) +
  geom_point() +
  labs(title = "Beta Diversity Estimation comparison",
       x = "Number of features",
       y = "Execution time in s",
       color = "method:",
       shape = "number of samples:",
       caption = "Execution time of estimating beta diversity as a function of number of features") +
  theme(legend.position = "bottom")
```
