---
title: "`r testmethod`"
subtitle: "Benchmarking computational efficiency of microbiome data containers"
author: "Giulio Benedetti and Leo Lahti"
date: "`r Sys.Date()`"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = paste0("../reports/figs/big_", testmethod, "_"))
```

## Overview

This report contains the benchmarking results of the largest analysed data set (`r mainExpName(bigdata)`) for the `r testmethod` operation.

## Data Characteristics

Full sample sizes by data set:

```{r samples, echo = FALSE, fig.width = 10, fig.height = 4 * length(containers)}
overview <- data.frame(Dataset = mainExpName(bigdata),
                       Samples  = ncol(bigdata),
		       Features = nrow(bigdata))
kable(overview)
```

Feature counts by data set:

```{r chars, echo = FALSE, fig.width = 10, fig.height = 4 * length(containers)}
big_feat <- big_df %>% select(Dataset, Rank, Features) %>%
     	            group_by(Dataset, Rank) %>%
                    summarize(Features = max(Features)) %>% # Variation due to removing zero rows & cols per round
		    unique() %>%
                    pivot_wider(names_from = Dataset, values_from = Features, values_fill = 0)
big_feat <- big_feat[order(big_feat[ , 2]), ] # Sort by the first dataset feature counts
kable(big_feat)
```

## Relative differences in execution time by sample size

```{r, echo = FALSE}
df <- big_df %>%
  rbind(df_benchmark %>% filter(Dataset == "GrieneisenTSData", Samples %in% c(100, 1000))) %>%  
  select(Features, Samples, Rank, ObjectType, Time) %>% 
  pivot_wider(names_from = c(ObjectType), values_from = Time) %>% 
  mutate(Ratio = tse / pseq)
```

```{r first_ratio, echo = FALSE, out.width="50%", fig.show="keep"}
ggplot(df, aes(x = Samples, y = Ratio, group = Rank, fill = Rank)) +
    geom_bar(position="dodge", stat="identity", color="black") + 
    labs(title = "Relative difference in execution times",
         x = "Samples (N)",
         y = "Relative time (TreeSE / phyloseq)",
         color = "Features (N)",
         caption = paste("Execution time ratio by samples (TreeSE/phyloseq): ", testmethod)) +
    scale_x_log10() +
    theme(legend.position="top") + 
    geom_hline(yintercept = 1, linetype = 2) 

if (length(tests[[testmethod]]) == 3) {
  
  df <- df %>% mutate(Ratio = tse / speedyseq)

  ggplot(df, aes(x = Samples, y = Ratio, group = Rank, fill = Rank)) +
    geom_bar(position="dodge", stat="identity", color="black") + 
    labs(title = "Relative difference in execution times",
         x = "Samples (N)",
         y = "Relative time (TreeSE / speedyseq)",
         color = "Features (N)",
         caption = paste("Execution time ratio by samples (TreeSE/speedyseq): ", testmethod)) +
    scale_x_log10() +
    theme(legend.position="top") + 
    geom_hline(yintercept = 1, linetype = 2) 

}
```
