---
title: "Benchmarking computational efficiency of TreeSE methods"
author: "Giulio Benedetti and Leo Lahti"
date: "`r Sys.Date()`"
---

```{r, include = FALSE}
# list data sets to run benchmark on
data_sets <- c("AsnicarF_2017", "GlobalPatterns", "SongQAData", "GrieneisenTSData", "SprockettTHData", "VincentC_2016", "BackhedF_2015", "ZeeviD_2015", "SilvermanAGutData")

# list sample sizes for random subsetting
sample_sizes <- c(10, 100, 1000)

source("data.R", local = knitr::knit_global())
source("experiment.R", local = knitr::knit_global())
```

```{r, include = FALSE}
# load tse objects and store them into
# a list of containers
containers <- mclapply(data_sets, load_dataset, mc.cores = numCores)

# make a data frame for each tse object
# and store them into a list of data frames
df <- lapply(containers, make_data_frame)
```

```{r, warning = FALSE}
source("melt_benchmark.R", local = knitr::knit_global())

# run benchmark on melting of tse and pseq with custom sample sizes
df_melt <- experiment_benchmark(containers, df, melt_tse_exec_time, melt_pseq_exec_time, sample_sizes)

# merge results from each data set into one data frame
df_melt <- merge_all(df_melt)

# plot execution time for melting subsets from
# the taxonomic rank "Order" and with 100 samples 
p1_melt <- plot_exec_time(df_melt, 100, "Order")
p1_melt

# plot execution time ratio for melting subsets from
# the taxonomic rank "Order" and with 1000 samples
p2_melt <- plot_ratio(df_melt, 1000, "Order")
p2_melt
```

```{r, include = FALSE}
# source("transform_benchmark.R", local = knitr::knit_global())
# df <- experiment_benchmark(containers, df)
```

```{r, include = FALSE}
# source("agglomerate_benchmark.R", local = knitr::knit_global())
# df <- experiment_benchmark(containers, df)
```

```{r, include = FALSE}
# source("alpha_benchmark.R", local = knitr::knit_global())
# df <- experiment_benchmark(containers, df)
```

```{r, include = FALSE}
# source("beta_benchmark.R", local = knitr::knit_global())
# df <- experiment_benchmark(containers, df)
```
