---
title: "Benchmarking TreeSE: melt"
author: "Giulio Benedetti and Leo Lahti"
date: "`r Sys.Date()`"
---


```{r setup, echo = FALSE}
theme_set(theme_bw(20))
```

```{r dataframe, echo = FALSE}
# create NA data frame to store the execution times throughout the for loop
df <- df %>% mutate(Melt = rep(NA, 14 * len_set * len_N),
                    MeltCommand = rep(c(rep("mia::meltAssay", len_set * len_N),
		                  rep("phyloseq::psMelt", len_set * len_N)), 7))
```

```{r, echo = FALSE}
# test melting for tse
melt_tse_exec_time <- function(tse) {
  
  start.time1 <- Sys.time()
  molten_tse <- mia::meltAssay(tse,
                       add_row_data = TRUE,
                       add_col_data = TRUE)
  end.time1 <- Sys.time()
    
  return(end.time1 - start.time1)
  
}

# test melting for pseq
melt_pseq_exec_time <- function(pseq) {
      
  start.time2 <- Sys.time()
  molten_pseq <- phyloseq::psmelt(pseq)
  end.time2 <- Sys.time()
    
  return(end.time2 - start.time2)
      
}
```

```{r iteration, echo = FALSE, warning = FALSE}
for (data_set in data_sets) {

  # define index of current data set
  cur_set <- which(data_sets == data_set)
  
  # repeat experiment for each taxonomic rank
  # Let us ignore Kingdom
  for (rank in 1:7) {
    
    # extract tse and pseq from list of containers
    tse <- containers[[cur_set]][[rank]]
    
    # repeat experiment for each sample size
    for (N in sample_sizes) {
    
      # select data sets at least as large as sample_size
      if (ncol(tse) >= N) {
      
        # define index of current sample size
        cur_N <- which(N == sample_sizes)
      
        # define df index to store results
        tse_ind <- cur_set + len_set * (cur_N - 1) + 2 * len_set * len_N * (rank - 1)
        pseq_ind <- cur_set + len_set * (cur_N + len_N - 1) + 2 * len_set * len_N * (rank - 1)
  
        # random subsetting
        subset_names <- sample(colnames(tse), N)
        sub_tse <- tse[ , colnames(tse) %in% subset_names]
        sub_pseq <- makePhyloseqFromTreeSummarizedExperiment(sub_tse)

        # store dimensions
        df$Features[tse_ind] <- nrow(sub_tse)
        df$Features[pseq_ind] <- nrow(sub_tse)
        df$Samples[tse_ind] <- ncol(sub_tse)
        df$Samples[pseq_ind] <- ncol(sub_tse)

        # test melting for tse
        df$Melt[tse_ind] <- melt_tse_exec_time(sub_tse)

        # test melting for pseq
        df$Melt[pseq_ind] <- melt_pseq_exec_time(sub_pseq)
    
      }
    }
  }  
}
```

```{r melting_features, echo = FALSE, fig.width=10, fig.height=8}
# Set breaks for log X scale
#m <- max(df$Features, na.rm=TRUE); r <- round(m, -(nchar(m)-1))
#v <- 10^seq(2, log10(r), by=1)
#v <- c(500, 1000, 2000, 5000, 10000)
# v <- unique(na.omit(df$Features))
cols <- c(tse="black", pseq="darkgray") # Ensure color order
#v <- unique(na.omit(df$Features))
ggplot(df %>% filter(!Rank=="Kingdom" & !is.na(Samples)),
        aes(x=Features, y=Melt, color=MeltCommand)) +
  geom_point() + 
  geom_line() +
  labs(title = "Melting comparison",
       x = "Features (D)",
       y = "Execution time (s)",
       color = "Method:",
       caption = "Execution time as a function of feature count.") +
  scale_x_log10() + # Log is often useful with sample size
  #scale_x_log10(breaks=v, labels=v) + # Log is often useful with sample size  
  scale_y_log10() + # Log is often useful with sample size
  scale_color_manual(values=cols[unique(df$ObjectType)]) +
  facet_grid(Samples ~ Dataset) + 
  theme(legend.position = "bottom")
```

# Feature set size vs. execution time 

Feature set size vs. execution time.

```{r melting_features_ratio, echo=FALSE, fig.width=6, fig.height=8, out.width="50%"}
dfsub <- df %>% filter(!Rank=="Kingdom" & !is.na(Samples) & !is.na(Melt)) %>%
                select(Dataset, Rank, Melt, Samples, Features, ObjectType)

df2 <- pivot_wider(dfsub, names_from=c(ObjectType), values_from=c(Melt)) %>%
         mutate(Ratio=tse/pseq)

ggplot(df2, aes(x=Features, y=Ratio, color=Samples, group=Samples)) +
        geom_point() +
        geom_line() +
	# scale_y_continuous(labels=scales::percent) +
	geom_hline(aes(yintercept=1), linetype=2, color="darkgray") + 	
        # scale_color_manual(values=cols[unique(df$ObjectType)]) +	
        facet_grid(Dataset ~ .) + 
	labs(title="Feature set size vs. time ratio",
	     x="Features (D)",
	     y="Ratio (tse/pseq)")
```


Execution time by taxonomic rank (not that feature set sizes may vary within ranks, between data sets).

```{r melting_features_ratio2, echo=FALSE, fig.width=7, fig.height=5, fig.show="keep", out.width="50%"}
dfsub <- df %>% filter(!Rank=="Kingdom" & !is.na(Samples) & !is.na(Melt)) %>%
                select(Dataset, Melt, Samples, Features, ObjectType, Rank)

df4 <- pivot_wider(dfsub,
                names_from=c(ObjectType),
	        values_from=c(Melt)) %>%
         mutate(Ratio=tse/pseq)

ggplot(df4, aes(x=Rank, y=Ratio, color=Samples)) +
        geom_boxplot(outlier.shape=NA) +
        geom_point() +	
	geom_hline(aes(yintercept=1), linetype=2, color="darkgray") + 	
	labs(title="Taxonomic rank vs. time ratio",
	     x="",
	     y="Ratio (tse/pseq)")

# -------------------------------------------------------------


ggplot(df4, aes(x=Rank, y=Ratio, group=Dataset, color=Samples)) +
        geom_point() +
        geom_line() +		
	geom_hline(aes(yintercept=1), linetype=2, color="darkgray") + 	
	labs(title="Taxonomic rank vs. execution time",
	     x="",
	     y="Ratio (tse/pseq)")

```






# Sample size vs. execution time


```{r melting_samples_ratio, echo=FALSE, fig.width=6, fig.height=4, fig.show="keep", out.width="50%"}
dfsub <- df %>% filter(!Rank=="Kingdom" & !is.na(Samples) & !is.na(Melt)) %>%
                select(Dataset, Melt, Samples, Features, ObjectType, Rank)

df3 <- pivot_wider(dfsub,
                names_from=c(ObjectType),
	        values_from=c(Melt)) %>%
         mutate(Ratio=tse/pseq)

for (dataset in unique(df3$Dataset)) {

  df3ds <- df3 %>% filter(Dataset == dataset)

  p <- ggplot(df3ds, aes(x=Samples, y=Ratio, color=Features, group=Rank)) +
        geom_point() +
        geom_line() +
	geom_hline(aes(yintercept=1), linetype=2, color="darkgray") + 	
        facet_grid(Dataset ~ .) + 
	labs(title=dataset,
	     x="Samples (N)",
	     y="Ratio (tse/pseq)")
  print(p)	    

}

```

