name: CI
on: push

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
      - uses: r-lib/actions/setup-r@v1
      
      - name: Test
      - run: Rscript -e 'print("Hello World!")'
