name: CI
on: push

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          working-directory: '.github'
            
      - name: Test
        run: |
          r -e 'library(dplyr)'
          Rscript -e '"Hello World!" %>% print()'
