name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@master
    
      - name: Setup R
      - uses: r-lib/actions/setup-r@v1
      - run: Rscript -e 'print("hello")'
