name: CI
on: push

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages(c("ggplot2", "dplyr", "scater", "parallel", "tidyr", "reshape", "knitr", "BiocManager"))'
          R -e 'BiocManager::install("phyloseq")'
            
      - name: Test
        run: |
          R -e 'library(reshape)'
          Rscript -e 'merge_all(data.frame(), data.frame())'
